// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/types'
import type * as prismicClient from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Item in *Collection → Gallery*
 */
export interface CollectionDocumentDataGalleryItem {
  /**
   * Image field in *Collection → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.gallery[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'thumb' | 'medium' | 'large'>
}

type CollectionDocumentDataSlicesSlice = QuoteSlice | TextSlice

/**
 * Content for Collection documents
 */
interface CollectionDocumentData {
  /**
   * Title field in *Collection*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the collection
   * - **API ID Path**: collection.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Featured Image field in *Collection*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.featuredImage
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredImage: prismic.ImageField<'thumb' | 'long'>

  /**
   * Gallery field in *Collection*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<Simplify<CollectionDocumentDataGalleryItem>>

  /**
   * Slice Zone field in *Collection*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CollectionDocumentDataSlicesSlice>
}

/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CollectionDocumentData>,
    'collection',
    Lang
  >

/**
 * Content for Collections documents
 */
interface CollectionsDocumentData {
  /**
   * Title field in *Collections*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of collections page
   * - **API ID Path**: collections.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Subtitle field in *Collections*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Subtitle in every collection's page
   * - **API ID Path**: collections.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField
}

/**
 * Collections document from Prismic
 *
 * - **API ID**: `collections`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CollectionsDocumentData>,
    'collections',
    Lang
  >

/**
 * Item in *Genre → collections*
 */
export interface GenreDocumentDataCollectionsItem {
  /**
   * collection field in *Genre → collections*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: genre.collections[].collection
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  collection: prismic.ContentRelationshipField<'collection'>
}

type GenreDocumentDataSlicesSlice = QuoteSlice | TextSlice

/**
 * Content for Genre documents
 */
interface GenreDocumentData {
  /**
   * Title field in *Genre*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the genre
   * - **API ID Path**: genre.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * collections field in *Genre*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: genre.collections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  collections: prismic.GroupField<Simplify<GenreDocumentDataCollectionsItem>>

  /**
   * Slice Zone field in *Genre*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: genre.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GenreDocumentDataSlicesSlice>
}

/**
 * Genre document from Prismic
 *
 * - **API ID**: `genre`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GenreDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<GenreDocumentData>, 'genre', Lang>

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Logo Title field in *Navigation*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the logo (eg: your name)
   * - **API ID Path**: navigation.logoTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  logoTitle: prismic.TitleField

  /**
   * Logo Subtitle field in *Navigation*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Logo description (eg: Photos by)
   * - **API ID Path**: navigation.logoSubtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  logoSubtitle: prismic.RichTextField

  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
  >

type PageDocumentDataSlicesSlice = ImageSlice | QuoteSlice | TextSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title of the page (eg: About me)
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField

  /**
   * Subtitle field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.TitleField

  /**
   * Contact Box? field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: page.hasContactBox
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasContactBox: prismic.BooleanField

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

/**
 * Item in *Settings → Tags*
 */
export interface SettingsDocumentDataTagsItem {
  /**
   * Image field in *Settings → Tags*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.tags[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'thumb' | 'square'>

  /**
   * Name field in *Settings → Tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional
   * - **API ID Path**: settings.tags[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Link field in *Settings → Tags*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional
   * - **API ID Path**: settings.tags[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField
}

/**
 * Item in *Settings → Contact Box Images*
 */
export interface SettingsDocumentDataContactBoxImagesItem {
  /**
   * Image field in *Settings → Contact Box Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contactBoxImages[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'thumb' | 'square'>
}

type SettingsDocumentDataSlicesSlice = never

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Name field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Name of your site (e.g. your name)
   * - **API ID Path**: settings.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField

  /**
   * Description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short description of your site
   * - **API ID Path**: settings.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Profile Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: a title above the summery
   * - **API ID Path**: settings.profileTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  profileTitle: prismic.TitleField

  /**
   * Profile Picture field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.profilePicture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profilePicture: prismic.ImageField<'thumb' | 'square'>

  /**
   * Profile Summery field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: a short summery about yourself
   * - **API ID Path**: settings.profileSummery
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  profileSummery: prismic.RichTextField

  /**
   * Profile CTA field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A call to action link after summery
   * - **API ID Path**: settings.profileCTA
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  profileCTA: prismic.RichTextField

  /**
   * Tags field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tags: prismic.GroupField<Simplify<SettingsDocumentDataTagsItem>>

  /**
   * Contact Box Title field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: A title for contact box section
   * - **API ID Path**: settings.contactBoxTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactBoxTitle: prismic.TitleField

  /**
   * Contact Box Subtitle field in *Settings*
   *
   * - **Field Type**: Title
   * - **Placeholder**: The contact box section's subtitle
   * - **API ID Path**: settings.contactBoxSubtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactBoxSubtitle: prismic.TitleField

  /**
   * Contact Box CTA field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: contact box call to action
   * - **API ID Path**: settings.contactBoxCTA
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactBoxCTA: prismic.RichTextField

  /**
   * Contact Box Images field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contactBoxImages[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contactBoxImages: prismic.GroupField<
    Simplify<SettingsDocumentDataContactBoxImagesItem>
  >

  /**
   * Copyright field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Copyright text in footer
   * - **API ID Path**: settings.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright: prismic.RichTextField

  /**
   * See Collection field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: See collection text
   * - **API ID Path**: settings.seeCollection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seeCollection: prismic.KeyTextField

  /**
   * See All Collections field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: See all collection text
   * - **API ID Path**: settings.seeAllCollection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seeAllCollection: prismic.KeyTextField

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    'settings',
    Lang
  >

export type AllDocumentTypes =
  | CollectionDocument
  | CollectionsDocument
  | GenreDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'thumb' | 'medium' | 'large' | 'square'>

  /**
   * Caption field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Caption under the image
   * - **API ID Path**: image.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField

  /**
   * Class Name field in *Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: the tailwind css class name
   * - **API ID Path**: image.primary.className
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  className: prismic.KeyTextField
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ImageSliceDefaultPrimary>,
  never
>

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceWidePrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Caption field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Caption under the image
   * - **API ID Path**: image.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField

  /**
   * Class Name field in *Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: the tailwind css class name
   * - **API ID Path**: image.primary.className
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  className: prismic.KeyTextField
}

/**
 * Wide variation for Image Slice
 *
 * - **API ID**: `wide`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceWide = prismic.SharedSliceVariation<
  'wide',
  Simplify<ImageSliceWidePrimary>,
  never
>

/**
 * Primary content in *Image → Primary*
 */
export interface ImageSliceRoundPrimary {
  /**
   * Image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<'thumb'>

  /**
   * Caption field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Caption under the image
   * - **API ID Path**: image.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  caption: prismic.RichTextField

  /**
   * Class Name field in *Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: the tailwind css class name
   * - **API ID Path**: image.primary.className
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  className: prismic.KeyTextField
}

/**
 * Round variation for Image Slice
 *
 * - **API ID**: `round`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceRound = prismic.SharedSliceVariation<
  'round',
  Simplify<ImageSliceRoundPrimary>,
  never
>

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault | ImageSliceWide | ImageSliceRound

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<'image', ImageSliceVariation>

/**
 * Primary content in *Quote → Primary*
 */
export interface QuoteSliceDefaultPrimary {
  /**
   * Quote field in *Quote → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Quote without quotation marks
   * - **API ID Path**: quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.TitleField

  /**
   * Source field in *Quote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Source of the quote
   * - **API ID Path**: quote.primary.source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField
}

/**
 * Default variation for Quote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<QuoteSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Quote*
 */
type QuoteSliceVariation = QuoteSliceDefault

/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Quote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteSlice = prismic.SharedSlice<'quote', QuoteSliceVariation>

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text with rich formatting
   * - **API ID Path**: text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TextSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      CollectionDocument,
      CollectionDocumentData,
      CollectionDocumentDataGalleryItem,
      CollectionDocumentDataSlicesSlice,
      CollectionsDocument,
      CollectionsDocumentData,
      GenreDocument,
      GenreDocumentData,
      GenreDocumentDataCollectionsItem,
      GenreDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataTagsItem,
      SettingsDocumentDataContactBoxImagesItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceWidePrimary,
      ImageSliceRoundPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageSliceWide,
      ImageSliceRound,
      QuoteSlice,
      QuoteSliceDefaultPrimary,
      QuoteSliceVariation,
      QuoteSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault
    }
  }
}
